#!/bin/sh

mercurial_configure()
{
  # If there is a BDSM installed python interpreter active, use it.
  if file_exists "${active_path}/bin/python"
  then
    export PYTHONPATH="${active_path}/"
  fi
}

mercurial_install()
{
  make install-bin PREFIX="${install_path}"
}

