#!/bin/sh

fossil_initialize()
{
  package define \
    file "${package_name}-src-${package_version}.${archive_format}" \
    dir "${package_name}-src-${package_version}"
}

fossil_install()
{
  move_file fossil to "${install_path}/bin/fossil" mode 0755
}
